server:
  port: 8222
spring:
  datasource:
    username: doadmin
    password: atnxoh6p92bfpnpo
    url: jdbc:h2:mem:accounts_db
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    startup:
      enabled: true
  server:
    address: 127.0.0.1
    port: 9001