server:
  port: 9222
spring:
  datasource:
    username: root
    password: welcome
    url: jdbc:mysql://accounts-db-do-user-4431921-0.b.db.ondigitalocean.com:3306/defaultdb
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false