server:
  port: 9222
spring:
  datasource:
    username: root
    password: welcome
    url: jdbc:mysql://localhost:3306/accounts_db
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false