server:
  port: 8222
spring:
  datasource:
    username: sa
    password: welcome
    url: jdbc:h2:mem:accounts_db
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
